### ISSUE TITLE
Minified File Clean Up

### ISSUE THREAD

**Issue by amydecat** [thinkshout/ts_grid#27]
Note: Dependent on there being a build script that compiles the asset files for locals and deployment.

- [ ] Add .gitkeep file to `dist` folder. 
- [ ] Remove both minified files (.css and .js) from `dist` folder.

**Comment by AmyTSwan** [comment]
@heypaxton - assigning to you for now since it's pertinent to your current project (FIPA). Feel free to assign to someone else, if you like.

**Comment by mariacha** [comment]
Since this gets done in the site-level, I'm closing.
